spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    # 批量更新添加 &allowMultiQueries=true
    url: jdbc:postgresql://192.168.104.194:6666/test?currentSchema=test&stringtype=unspecified&allowMultiQueries=true
    username: postgres
    password: postgres
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      aop-patterns: com.joker.*
      filter:
        stat:
          enabled: true
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
            # 批量更新开启
            multi-statement-allow: true
            none-base-statement-allow: true
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat, wall
  redis:
    # Redis服务器地址
    host: 192.168.104.205
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 4
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: 123456
    lettuce:
      pool:
        # 最大阻塞等待时间，负数表示没有限制
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中最大连接数，负数表示没有限制
        max-active: 20
#Mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  # 创建实体类别名
  type-aliases-package: com.hit.edu.po.**
  # 创建枚举值
  type-enums-package: com.hit.edu.enums.**
  global-config:
    db-config:
      # 数据库前缀
      table-prefix: t_
      #需要配置的逻辑删除数据库字段
      logic-delete-field: is_deleted
      #配置逻辑删除字段为1是删除
      logic-delete-value: b'1'
      #配置逻辑删除字段为1是删除
      logic-not-delete-value: b'0'
      # 主键自增策略
      #id-type: auto
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: true
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.JacksonTypeHandler
